Homework2
made-ml-in-prod-2022/rinat pull request #2
Opened 2022-05-29 16:39 UTC by Xrenya

Привет!
Самооценка:

- [x]  Весь код должен находиться в том же репозитории, но в отдельной папке online_inference.
- [x] Оберните inference вашей модели в rest сервис на FastAPI, должен быть endpoint /predict (3 балла)
- [x] Напишите endpoint /health (1 балл), должен возращать 200, если ваша модель готова к работе (такой чек особенно актуален если делаете доп задание про скачивание из хранилища)
- [x] Напишите unit тест для /predict (3 балла) (https://fastapi.tiangolo.com/tutorial/testing/, https://flask.palletsprojects.com/en/1.1.x/testing/)
- [x] Напишите скрипт, который будет делать запросы к вашему сервису -- 2 балла
- [x] Напишите dockerfile, соберите на его основе образ и запустите локально контейнер(docker build, docker run), внутри контейнера должен запускать сервис, написанный в предущем пункте, закоммитьте его, напишите в readme корректную команду сборки (4 балл)
- [x] Опубликуйте образ в https://hub.docker.com/, используя docker push (вам потребуется зарегистрироваться) (+2 балла)
- [x] Напишите в readme корректные команды docker pull/run, которые должны привести к тому, что локально поднимется на inference ваша модель (1 балл) Убедитесь, что вы можете протыкать его скриптом из пункта 3
- [x] Проведите самооценку(распишите в реквесте какие пункты выполнили и на сколько баллов, укажите сумму баллов) -- 1 балл
3+1+3+2+4+2+1+1=17
Дополнительная часть:

- [x] Ваш сервис скачивает модель из S3 или любого другого хранилища при старте, путь для скачивания передается через переменные окружения (+2 доп балла)
- [ ] Оптимизируйте размер docker image (+2 доп балла) (опишите в readme.md что вы предприняли для сокращения размера и каких результатов удалось добиться -- должно получиться мини исследование, я сделал тото и получился такой-то результат) https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
- [ ] Сделайте валидацию входных данных https://pydantic-docs.helpmanual.io/usage/validators/ (например, порядок колонок не совпадает с трейном, типы, допустимые максимальные и минимальные значения, проявите фантазию, это доп. баллы, проверка не должна быть тривиальной) (вы можете сохранить вместе с моделью доп информацию, о структуре входных данных, если это нужно) -- 2 доп балла https://fastapi.tiangolo.com/tutorial/handling-errors/ -- возращайте 400, в случае, если валидация не пройдена
+2
Итого: 19 баллов

2022-06-19 21:39 UTC, SVizor42 commented on online_inference/src/utils.py
> +def setup_logging(logging_yaml_config_fpath):
str type?

2022-06-19 21:43 UTC, SVizor42 commented on online_inference/Dockerfile
> +RUN python -m venv venv
В целом, в виртуальном окружении тут нет необходимости, все-таки приложение для инференса внутри отдельного контейнера

2022-06-19 21:43 UTC, SVizor42 commented on online_inference/README.md
> +docker docker run -p 1234:5000 --name cont_app app
Лишний `docker`

2022-06-19 21:44 UTC, SVizor42 commented on online_inference/README.md
> +
Добавь еще команду для сборки образа плиз

2022-06-19 21:49 UTC, SVizor42 requested changes
Все хорошо. Посмотри комментарии.

Еще добавлю:
1. Папки `.idea` лучше тоже добавить в `.gitignore`
2. По поводу доп пункта со скачиванием модели: здорово, что задействовал `dvc`, просто тут ожидается, что модель будет скачиваться при старте приложения (startup event). Попробуй автоматизировать эту часть

2022-06-20 13:19 UTC, Xrenya commented on online_inference/src/utils.py
> +def setup_logging(logging_yaml_config_fpath):
done!

2022-06-20 13:20 UTC, Xrenya commented on online_inference/Dockerfile
> +RUN python -m venv venv
просто он дает предупреждение красным цветом и просит обновить pip, поэтому сделал venv

2022-06-20 13:24 UTC, Xrenya commented on online_inference/README.md
> +docker docker run -p 1234:5000 --name cont_app app
done!

2022-06-20 13:24 UTC, Xrenya commented on online_inference/README.md
> +
done!

2022-06-20 13:31 UTC, Xrenya commented
`модель будет скачиваться при старте приложения (startup event)`
добавлю комманду в Docker и протестирую: `RUN dvc pull`

2022-06-20 13:31 UTC, Xrenya commented
Done: `Папки .idea лучше тоже добавить в .gitignore`

2022-06-23 05:01 UTC, Xrenya commented
@SVizor42 
`RUN dvc pull` Done!
```
Step 10/12 : RUN dvc pull
 ---> Running in *
Everything is up to date.
Removing intermediate container *
```

2022-06-23 06:51 UTC, SVizor42 approved these changes
Хорошо.

**Сумма: 19 баллов**

Можно мерджить

2022-06-23 09:03 UTC, merged